<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">     <!--不需要name,因为作为子文件-->
    <xacro:include filename="$(find my_robot_description)/urdf/common/common_inertia.xacro"/>
    <xacro:macro name="base_xacro" params="length radius">  
        <link name="base_link">
        <!-- 部件外观 -->
            <visual>
                <!-- 沿着自己几何中心的偏移和旋转 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>    <!--碰撞-->
                 <!-- 沿着自己几何中心的偏移和旋转 -->
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <!-- 几何形状 -->
                <geometry>
                    <!-- 圆柱体 -->
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <!-- 材质颜色 -->
                <material name="white">
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${radius}" h="${length}"/>    <!--kg-->
        </link>

        <link name="base_footprint" />

        <joint name="joint_name" type="fixed">
            <origin xyz="0.0 0.0 ${length/2.0+0.032-0.001}" rpy="0.0 0.0 0.0"/>
            <parent link="base_footprint"/>
            <child link="base_link"/>
        </joint>

        <gazebo reference="base_link">
            <material>Gazebo/Green</material>
        </gazebo>
        
    </xacro:macro>
</robot>
